# Is this a strange file?
# as C developer you have to be familiar with makefiles
# we will explain them in our session, but if you are curios and you don't
# like to wait you can learn about Makefiles here:
# https://makefiletutorial.com/
# Happy learning

SRC = main.c print_table.c rand_fill_table.c get_third_largest.c
PRO_NAME= prog

all:
	gcc $(SRC) -o $(PRO_NAME)

clean:
	rm $(PRO_NAME)
